### ISSUE TITLE
Recherche par surnom + bouffe

### ISSUE THREAD

**Issue by Swy7ch** [Pier4413/Barbu#1]
Je te laisse ici pour avoir une trace, la recherche par surnom ne fonctionne pas sur la nouvelle appli, mais ils sont bien affichés quand on cherche avec le nom.

Sinon il manque la bouffe mais ça on s'arrange

**Comment by Pier4413** [comment]
Corrigé + Correction bug lié à l'affiche des 20 dernières actions

Ajout de la nourriture dans une prochaine version

**Comment by Pier4413** [comment]
Nouvelle version car correction d'un autre bug lié à la recherche par surnom.
